# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$(document).ready ->
  $('.owl-carousel').owlCarousel
    slideSpeed: 300
    autoPlay: true
    navigation: false
    pagination: false
    singleItem: true
  return

# ---
# generated by js2coffee 2.2.0